<?php

/**
 * Implements hook_theme().
 */
function wunderhub_client_theme() {
  return [
    'wunderhub_client_team' => [
      'render element' => 'element',
    ],
    'wunderhub_client_team__member' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function wunderhub_client_preprocess_html(&$variables) {
  if ($variables['root_path'] == 'team') {
    $variables['html_attributes']['ng-app'] = 'wunderhub-client';
  }
}
